insert into User (name, surname, email, password, address, verificationCode, type) values
	("Luca","Patron","lucapatron@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via del pigneto 11, Roma","","registered"),
	("Massimo","Casale","massimocasale@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via pompei 2, Roma","","seller"),
	("Andrea","Vesco","andreavesco@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via luni 15, Roma","","seller"),
	("Andrea","Guerini","andreaguerini@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via iberia 100, Roma","", "seller"),
	("Giovanni","Moceri","giovannimoceri@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via pomezia 1, Roma","","seller"),
	("Daniele","Bonetti","danielebonetti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via concordia 30, Roma","","seller"),
	("Guglielmo","Berisso","guglielmoberisso@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via roma 115, Civitavecchia","","seller"),
	("Michele","Cibaldi","michelecibaldi@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via roma 10, Civitavecchia","","seller"),
	("Michele","Tebaldi","micheletebaldi@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via roma 2, Civitavecchia","","seller"),
	("Andrea","Costa","andreacosta@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via buonarroti 15, Civitavecchia","","seller"),
	("Lorenzo","Turelli","lorenzoturelli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via buonarroti 30, Civitavecchia","","seller"),
	("Giordano","Mozzi","giordanomozzi@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via verdi 13, Aprilia","","seller"),
	("Alberto","Scapolo","albertoscapolo@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via verdi 50, Aprilia","","seller"),
	("Andrea","Belometti","andreabelometti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale europa 12, Aprilia","","seller"),
	("Alberto","Aliverti","albertoaliverti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale europa 30, Aprilia","","seller"),
	("Giuliano","Cane","giulianocane@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale europa 22, Aprilia","","seller"),
	("Mario","Passanante","mariopassanante@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via piave 15, Frosinone","","seller"),
	("Sergio","Sisti","sergiosisti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via piave 22, Frosinone","","seller"),
	("Domenico","Battagliola","domenicobattagliola@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via piave 55, Frosinone","","seller"),
	("Alberto","Ribolti","albertoribolti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mazzini 11, Frosinone","","seller"),
	("Riccardo","Crisina","riccardocrisina@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mazzini 111, Frosinone","","seller"),
	("Massimo","Bettinsoli","massimobettinsoli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via dalmazia 1, Viterbo","","seller"),
	("Marco","Gatta","marcogatta@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via dalmazia 3, Viterbo","","seller"),
	("Oscar","Gatto","oscargatto@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via venezia giulia 12, Viterbo","","seller"),
	("Bruno","Ferrari","brunoferrari@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via venezia giulia 15, Viterbo","","seller"),
	("Marco","Gaggioli","marcogaggioli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via dalmazia 45, Viterbo","","seller"),
	("Roberto","Miatto","robertomiatto@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale lombardia 113, Milano","","seller"),
	("Emanuele","Peli","emanuelepeli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale lombardia 22, Milano","","seller"),
	("Francesco","Polini","francescopolini@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale lombardia 111, Milano","","seller"),
	("Lucia","Galliani","luciagalliani@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via gulli 15, Milano","","seller"),
	("Anna","Gualandi","annagualandi@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via gulli 19, Milano","","seller"),
	("Emanuele","Puna","emanuelepuna@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via ratti 23, Rho","","seller"),
	("Paolo","Sabbiadini","paolosabbiadini@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via ratti 50, Rho","","seller"),
	("Sabrina","Baroli","sabrinabaroli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via ratti 1, Rho","","seller"),
	("Daniele","Pali","danielepali@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via ratti 50, Rho","","seller"),
	("Eugenio","Piccinelli","eugeniopiccinelli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via ratti 3, Rho","","seller"),
	("Carlo","Ferrari","carloferrari@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via roma 11, Mantova","","seller"),
	("Andrea","Ronzoni","andrearonzoni@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via roma 133, Mantova","","seller"),
	("Marco","Forti","marcoforti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via roma 55, Mantova","","seller"),
	("Gianfranco","Frati","gianfrancofrati@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via roma 2, Mantova","","seller"),
	("Martina","Scio","martinascio@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via milano 24, Mantova","","seller"),
	("Paolo","Taranto","paolotaranto@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mazzini 11, Brescia","","seller"),
	("Aldo","Olli","aldolli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mazzini 50, Brescia","","seller"),
	("Riccardo","Bailo","riccardobailo@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mazzini 100, Brescia","","seller"),
	("Fabrizio","Vicari","fabriziovicari@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mazzini 22, Brescia","","seller"),
	("Andrea","Giaccopo","andreagiaccopo@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mazzini 38, Brescia","","seller"),
	("Luigi","Carlini","luigicarlini@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via verdi 15, Bergamo","","seller"),
	("Mauro","Ferrari","mauroferrari@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via verdi 20, Bergamo","","seller"),
	("Attilio","Bonetti","attiliobonetti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq", "via verdi 30, Bergamo","","seller"),
	("Silvia","Marini","silviamarini@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale roma 223, Bergamo","","seller"),
	("Gianfranco","Mazzola","gianmazzola@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale roma 30, Bergamo","","seller"),
	("Carlo","Ovi","carlovi@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","corso cavour 11 Verona","","seller"),
	("Andrea","Lussana","andrealussana@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","corso cavour 30 Verona","","seller"),
	("Maurizio","Zanni","mauriziozanni@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","corso cavour 100 Verona","","seller"),
	("David","Reid","davidreid@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via duomo 2 Verona","","seller"),
	("Tarcisio","Bonomi","tarcisiobonomi@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via duomo 22 Verona","","seller"),
	("Giulio","Felloni","giuliofelloni@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale giraldi 15 Bassano","","seller"),
	("Mario","Bariselli","mariobariselli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale diaz 22 Bassano","","seller"),
	("Luca","Murru","lucamurru@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale diaz 100 Bassano","","seller"),
	("Arturo","Cavalli","arturocavalli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale giraldi 100 Bassano","","seller"),
	("Antonio","Belotti","antoniobelotti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale giraldi 23 Bassano","","seller"),
	("Gianmarco","Rossi","gianmarcorossi@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","calle oche 1 Venezia","","seller"),
	("Alberto","Gnutti","albertognutti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","calle oche 3 Venezia","","seller"),
	("Romolo","Becchetti","romolobecchetti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","calle longa 1 Venezia","","seller"),
	("Mario","Beccaria","mariobeccaria@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","calle longa 15 Venezia","","seller"),
	("Flavio","Gandolfi","flaviogandolfi@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","calle longa 10 Venezia","","seller"),
	("Carlo","Incerti","carloincerti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via piave 15 Padova","","seller"),
	("Massimo","Ermini","massimoermini@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via piave 30 Padova","","seller"),
	("Giustino","De Sanctis","giustinodesanctis@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via piave 24 Padova","","seller"),
	("Emanuele","Tabacchi","emanuelesmokes@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via piave 19 Padova","","seller"),
	("Loris","Gianotti","lorisgianotti@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via piave 16 Padova","","seller"),
	("Luca","Pascolini","lucapascolini@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via cavour 2 Belluno","","seller"),
	("Andrea","Ferrari","andreaferrari@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via cavour 15 Belluno","","seller"),
	("Corrado","Zobbio","corradozobbio@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via cavour 67 Belluno","","seller"),
	("Alessio","De Angelis","alessiodeangelis@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via cavour 100 Belluno","","seller"),
	("Marco","Bertocchi","marcobertocchi@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via cavour 123 Belluno","","seller"),
	("Filippo","Ciocca","filippociocca@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via grazioli 23 Trento","","seller"),
	("Filippo","Tanfoglio","filippotanfoglio@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via verdi 11 Trento","","seller"),
	("Alessandro","Franzoi","franzoiale@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via roma 12 Trento", "","seller"),
	("Paolo","Berton","paoloberton@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale verona 112 Trento","","seller"),
	("Luigi","Mion","luigimion@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mazurana 12 Trento","","seller"),
	("Daniele","Spataro","spatarodaniele@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale de gasperi 11 Cles","","seller"),
	("Roberto","Angeli","robertoangeli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale de gasperi 23 Cles","","seller"),
	("Achille","Donati","achilledonati@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale de gasperi 29 Cles","","seller"),
	("Giulio","Olivini","giuliolivini@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale de gasperi 34 Cles","","seller"),
	("Paolo","Nolli","paolonolli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","viale de gasperi 50 Cles","","seller"),
	("Paolo","Basilico","paolobasilico@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mantova 23 Arco","","seller"),
	("Maria","Gabulli","mariagabulli@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mantova 50 Arco","","seller"),
	("Sergio","Solero","sergiosole@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mantova 22 Arco","","seller"),
	("Luca","Vitali","lucavitali@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mantova 10 Arco", "","seller"),
	("Anna","Levorato","annalevorato@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via mantova 45 Arco","","seller"),
	("Antonio","Ariuto","antonioariuto@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via esterle 15 Cavalese","","seller"),
	("Mario","Ronzoni","marioronzoni@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via esterle 23 Cavalese","","seller"),
	("Giacomo","Zorzi","giacominz@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via esterle 34 Cavalese","","seller"),
	("Massimo","Gussago","maxgussavo@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via esterle 28 Cavalese","","seller"),
	("Eleonora","Di Stefano","elestefano@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via esterle 100 Cavalese","","seller"),
	("Edoardo","Alfano","edoalfano@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via garibaldi 2 Predazzo","","seller"),
	("Patrizia","Serafini","serafinipatrizia@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via garibaldi 12 Predazzo","","seller"),
	("Giorgio","Maule","maulegiorgio@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via garibaldi 25 Predazzo","","seller"),
	("Massimo","Vita","vitamax@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via garibaldi 50 Predazzo","","seller"),
	("Claudio","Filippi","claudiofilippi@email.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq","via garibaldi 100 Predazzo","","seller"),
	("Nicolò","Pomini","nicolopomini@gmail.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq"," ","1","admin"),
	("Gabriele","Maurina","gabrielemaurina95@gmail.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq"," ","","admin"),
	("Michele","Armellini","michelearmellini@gmail.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq"," ","","admin"),
	("Marco","Merlin","marcomerlin@gmail.com","$2a$10$2Gs/9VUQJTfuCnH9zVSndusINLOvBuewsl.Q6znYMijiKls4ZIlUq"," ","","admin");

	insert into Shop (name,website,address,lat,lon,openingHours,userId,imagePath) values
		("Le Group","legroupefashion.com","via del corso, 282, 00187 Roma",41.8972018,12.4820151,"Lun-Dom: 10 - 20",2,"img/1.JPG"),
		("Le Group","legroupefashion.com","via nazionale, 195, 00184 Roma",41.8996288,12.4912549,"Lun-Dom: 10 - 20",2,"img/1.JPG"),
		("Feltrinelli","lafeltrinelli.it","Largo di Torre Argentina, 5/A, 00186 Roma",41.89611,12.47663,"Lun-Dom 9 - 21",3,"img/2.jpeg"),
		("Feltrinelli","lafeltrinelli.it","Via Vittorio Emanuele Orlando, 78/81, 00185 Roma",41.9034977,12.4951719,"Lun-Dom 9 - 21",3,"img/3.jpeg"),
		("Feltrinelli","lafeltrinelli.it","Piazza Colonna, 31-35, 00187 Roma",41.8849605,12.5107732,"Lun-Dom 9 - 21",3,"img/3.jpeg"),
		("Media Market Elettronica","gbconline.it","Via Simone de Saint Bon, 20/22, 00195 Roma",41.9115157,12.456992,"Lun-Sab, 9-13, 15.30-19",4,"img/4.jpg"),
		("Magliette Personalizzate Express","t-shirtmaker.it","Via Federico Cesi, 56, 00193 Roma",41.90809309999999,12.4708127,"Lun-Sab 10-19",5,"img/5.jpg"),
		("Magliette Personalizzate Express","t-shirtmaker.it","Via Ennio Quirino Visconti, 35, Roma",41.9080575,2.470779,"Lun-Sab 10-19",5,"img/5.jpg"),
		("Deatronic Srl","deatronic.com","Via Giulianello, 1, 00178 Roma",41.8669907,12.5389056,"",6,"img/6.jpg"),
		("G.B. Elettronica","stores.ebay.it","Viale dei Consoli, 7, 00175 Roma",41.8638302802915,12.5571177802915,"Lun-Sab 9-13, 16-20",6,"img/7.jpg");

insert into Item (name, description, category, price, shopId) values
	("iPhone", "Apple iPhone", "electronics",749.99,10),
	("iPhone", "Apple iPhone", "electronics",749.99,9),
	("I Pilastri della Terra", "Libro 'I Pilastri della terra', Ken Follett","books",15.49,3),
	("I Pilastri della Terra", "Libro 'I Pilastri della terra', Ken Follett","books",19.99,4),
	("I Pilastri della Terra", "Libro 'I Pilastri della terra', Ken Follett","books",12.34,5);

insert into Picture (path,itemID) values
	("img/iphone.jpg",1),
	("img/iphone.jpg",2),
	("img/iphone7.jpg",1),
	("img/iphone7.jpg",2),
	("img/pilastri.jpg",3),
	("img/pilastri.jpg",4),
	("img/pilastri.jpg",5);

insert into ShopReview (reviewText, reply, userId, shopId, reviewTime, score) values
	("Ottimo negozio", null, 22, 4, now(), 5),
	("Bello", "Grazie", 31, 4, now(), 5),
	("Cosi cosi", null, 22, 4, now(), 2);

insert into ItemReview (reviewText, reply, userId, itemId, reviewTime, score) values
	("Bello",null, 11, 3, now(), 4),
	("Lungo!!","eddai!", 11, 3, now(), 3);

insert into Notification (author,recipient, notificationTime, notificationText, type, link) values
	(12,1,"2015-2-3","Notifica di prova",'newcommentshop',""),
	(12,1,"2014-2-3","Notifica 2",'replycommentshop',""),
	(12,1,"2000-4-23","3",'newcommentitem',""),
	(12,1,"2016-2-3","4",'replycommentitem',"");

insert into Purchase (userId, itemId, quantity, purchaseTime) values
	(1,1,2,now());

insert into Complaint (purchaseId, complaintTime, complaintText, status) values
	(1,now(),"Complaint di prova.","new");
